TeamViewer User Settings
# It is not recommended to edit this file manually


[int32] ConfigurationCoPilotEnabled = 1
[int32] ConfigurationLAPSEnabled = 1
[int32] ConfigurationRMAssetReportingEnabled = 1
[int32] ConfigurationSessionSummaryEnabled = 1
[int32] Enable1EClient = 1
[int32] LastCorrectorRun = 2
[int32] MainWindowSize = 1890 1006 58 15
[bin  ] SUID = a1bd36199caf42cbb80a3c789e5067af
